import { Badge, Button, Card, FeaturePill, Metric, Nav, PlatformStatusBadge, Shell, ToolStatusBadge } from "@/components/ui";
import { boosts, reviews, tools } from "@/lib/data";

export default function DashboardPage() {
  const pendingAppeals = reviews.filter((review) => review.appealStatus === "Pending Appeal").length;
  return (
    <Shell>
      <Nav />
      <section className="mt-12"><Badge>Seller Area</Badge><h1 className="mt-4 text-5xl font-black">Seller Dashboard</h1><p className="mt-3 max-w-2xl text-slate-400">Manage products, features, boosts, reviews, analytics, billing, and settings from one place.</p></section>
      <section className="mt-8 grid gap-4 md:grid-cols-4"><Metric label="Product Slots" value="3 / 10" detail="Pro plan"/><Metric label="Active Boosts" value="1" detail="Sponsored visibility"/><Metric label="Clicks" value="2.1k" detail="+18.6%"/><Metric label="Appeals" value={String(pendingAppeals)} detail="Admin review"/></section>
      <section className="mt-8 grid gap-6 xl:grid-cols-[1fr_360px]">
        <div className="space-y-6">
          <Card className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">Seller Alerts</h2><Badge tone="cyan">Actionable</Badge></div><div className="grid gap-3 md:grid-cols-3">{[["Boost ending soon","PhantomX boost ends in 8 days."],["Product pending review","Shadow Overlay is waiting approval."],["Review appeal pending","One appeal is in admin review."]].map(([title,text])=><div key={title} className="rounded-2xl border border-white/10 bg-slate-950/50 p-4"><div className="font-semibold">{title}</div><p className="mt-1 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></Card>
          <Card id="products" className="overflow-hidden"><div className="border-b border-white/10 p-5"><h2 className="text-xl font-bold">Products</h2><p className="mt-1 text-sm text-slate-400">Control product status, features, boosts, and visibility.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Product</th><th className="px-5 py-4">Platform</th><th className="px-5 py-4">Tool Status</th><th className="px-5 py-4">Features</th><th className="px-5 py-4">Stats</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{tools.map((tool)=><tr key={tool.slug} className="border-b border-white/5 last:border-0"><td className="px-5 py-5"><div className="font-semibold">{tool.name}</div><div className="text-xs text-slate-500">{tool.game} • {tool.category}</div></td><td className="px-5 py-5"><PlatformStatusBadge value={tool.platformStatus}/></td><td className="px-5 py-5"><ToolStatusBadge value={tool.toolStatus}/></td><td className="px-5 py-5"><div className="flex flex-wrap gap-1.5">{tool.features.slice(0,3).map((feature)=><FeaturePill key={feature}>{feature}</FeaturePill>)}</div></td><td className="px-5 py-5"><div>★ {tool.rating || "—"}</div><div className="text-xs text-slate-500">{tool.clicks} clicks</div></td><td className="px-5 py-5 text-right"><button className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2 text-sm font-semibold">Edit</button></td></tr>)}</tbody></table></div></Card>
          <Analytics />
        </div>
        <aside className="space-y-6"><Card className="p-5"><h2 className="text-xl font-bold">Boost Center</h2><div className="mt-4 space-y-3">{boosts.map((boost)=><div key={boost.product} className="rounded-2xl border border-white/10 bg-slate-950/50 p-4"><div className="flex items-center justify-between"><div className="font-semibold">{boost.product}</div><Badge tone={boost.status === "Active" ? "green" : "amber"}>{boost.status}</Badge></div><div className="mt-2 text-xs text-slate-500">{boost.package} • {boost.spend} • {boost.clicks} clicks</div></div>)}</div></Card><Card className="p-5"><h2 className="text-xl font-bold">Review Appeals</h2><p className="mt-2 text-sm leading-6 text-slate-400">Sellers can appeal reviews, but cannot edit or delete them. Admin makes final decisions.</p></Card><Card className="p-5"><h2 className="text-xl font-bold">Billing</h2><p className="mt-2 text-sm text-slate-400">Current plan: Pro. 7 product slots remaining.</p><div className="mt-4"><Button href="/pricing" variant="secondary">Manage plan</Button></div></Card></aside>
      </section>
    </Shell>
  );
}

function Analytics(){return <Card className="p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Analytics Overview</h2><Badge tone="cyan">Last 7 days</Badge></div><div className="mt-6 h-44 rounded-2xl border border-white/10 bg-slate-950/50 p-4"><div className="flex h-full items-end gap-2">{[28,38,44,62,48,52,70,64,58,76,82,68,74,88].map((height,index)=><div key={index} className="flex-1 rounded-t-md bg-gradient-to-t from-purple-600/40 to-cyan-300/90" style={{height:`${height}%`}} />)}</div></div></Card>}
