import { notFound } from "next/navigation";
import { getSeller, tools, offers, paymentsFor } from "@/lib/data";
import { Badge, Button, Card, Nav, SectionTitle, Shell, Stat } from "@/components/ui";
import { riskTone } from "@/lib/helpers";
import { ToolCard } from "@/components/tool-card";

export default function SellerPage({ params }: { params: { sellerSlug: string } }) {
  const seller = getSeller(params.sellerSlug);
  if (!seller) notFound();
  const sellerTools = tools.filter((tool) => tool.providerSlug === seller.slug);
  const sellerOffers = offers.filter((offer) => offer.sellerSlug === seller.slug);
  const payments = paymentsFor(seller.paymentIds);
  return <Shell><Nav /><section className="mt-12 rounded-3xl border border-purple-400/30 bg-white/[0.035] p-8"><div className="grid gap-8 lg:grid-cols-[1fr_330px]"><div><div className="flex flex-wrap gap-2"><Badge tone={seller.kind === "Official Provider" ? "green" : "purple"}>{seller.kind}</Badge><Badge tone={riskTone(seller.status) as any}>{seller.status}</Badge></div><h1 className="mt-4 text-5xl font-black">{seller.name}</h1><p className="mt-4 max-w-3xl text-slate-400">{seller.description}</p></div><Card className="p-5"><div className="text-sm text-slate-400">Seller trust</div><div className="mt-3 text-5xl font-black">{seller.trustScore}/100</div><div className="mt-2 text-sm text-slate-500">Dispute rate {seller.disputeRate} • Response {seller.responseTime}</div></Card></div></section><section className="mt-8 grid gap-4 md:grid-cols-4"><Stat label="Plan" value={seller.plan} detail="Seller tier" /><Stat label="Offers" value={seller.offers} detail="Product/reseller listings" /><Stat label="Joined" value={seller.joined} detail="Seller history" /><Stat label="Payments" value={payments.length} detail="Accepted methods" /></section><SectionTitle eyebrow="Accepted payments" title="Payment profile" text="Users can choose a seller based on the payment method they can actually use." /><section className="mt-6 grid gap-4 md:grid-cols-4">{payments.map((method) => <Card key={method.id} className="p-5"><div className="flex items-center justify-between gap-2"><h3 className="font-black">{method.name}</h3><Badge tone={riskTone(method.risk) as any}>{method.risk}</Badge></div><p className="mt-3 text-sm leading-6 text-slate-400">{method.note}</p></Card>)}</section>{sellerOffers.length > 0 && <><SectionTitle eyebrow="Reseller offers" title="Available offers" /><section className="mt-6 grid gap-4">{sellerOffers.map((offer) => { const tool = tools.find((item) => item.slug === offer.toolSlug); return <Card key={offer.toolSlug} className="p-5"><div className="grid gap-4 lg:grid-cols-[1fr_220px_180px]"><div><h3 className="text-xl font-black">{tool?.name}</h3><p className="mt-1 text-sm text-slate-500">{offer.kind} • Delivery {offer.delivery} • {offer.stock}</p><div className="mt-3 flex flex-wrap gap-2">{paymentsFor(offer.paymentIds).map((method) => <Badge key={method.id} tone={riskTone(method.risk) as any}>{method.name}</Badge>)}</div></div><Stat label="Trust" value={`${offer.trustScore}/100`} /><div className="text-right"><div className="text-2xl font-black">{offer.price}</div><Button href={`/tools/${offer.toolSlug}`} className="mt-3 w-full">View tool</Button></div></div></Card>; })}</section></>}<SectionTitle eyebrow="Official products" title="Seller catalog" /><section className="mt-6 grid gap-4">{sellerTools.map((tool) => <ToolCard key={tool.slug} tool={tool} />)}</section></Shell>;
}
